// /*
// A storage folder (i.e. '.prompt-scaffold') is created in each workspace folder.
// This folder will include the workspace files in the 'workspace-info' subdirectory.
// If it's the root workspace, the storage folder will also include the project-info and out subdirectories.
// Users configure the extension functionality by editing these files.
// */

// // Describes storage folder structure
// export const STORAGE_FOLDER_STRUCTURE = {
//     // This exists in every storage folder (all workspaces)
//     WORKSPACE_INFO_DIR: 'workspace-folder-info',     // Contains workspace folder-specific files     
//     // These exist only in the workspace root's storage folder
//     PROJECT_INFO_DIR: 'project-info',   // Contains workspace-specific files  
//     PROMPT_OUT_DIR: 'prompt-out'                            // Contains prompt output files generated by the extension 
// };

// // Describes project info files
// // These control the project description and apply to entire project
// export const PROJECT_INFO_FILES = {
//     // FILES IN PROJECT INFO DIR
//     PROJECT_INFO_SYSTEM_PROMPT: 'system-prompt.txt',               // Base prompt used
//     PROJECT_INFO_DESCRIPTION: 'project-description.txt',   // Description of whole system
//     PROJECT_INFO_SESSION_GOALS: 'session-goals.txt',               // Current development session goals
//     PROJECT_INFO_CONTEXT_STRUCTURE_INCLUDE_GITIGNORE: 'context.structure.include.gitignore', // Files to include in structure summary
//     PROJECT_INFO_CONTEXT_STRUCTURE_EXCLUDE_GITIGNORE: 'context.structure.exclude.gitignore', // Files to exclude from structure summary
//     PROJECT_INFO_CONTEXT_CONTENT_INCLUDE_GITIGNORE: 'context.content.include.gitignore',     // Files to include in content summary
//     PROJECT_INFO_CONTEXT_CONTENT_EXCLUDE_GITIGNORE: 'context.content.exclude.gitignore'      // Files to exclude from content summary
// };

// // Describes workspace info files
// // These control which files from the workspace folder are included in the context
// export const WORKSPACE_INFO_FILES = {
//     // FILES IN WORKSPACE INFO DIR
//     WORKSPACE_FOLDER_DESCRIPTION: 'workspace-folder-description.txt',        // Description of specific workspace (project w/in system)
//     WORKSPACE_FOLDER_CONTEXT_STRUCTURE_INCLUDE_GITIGNORE: 'workspace-folder-context-structure-include.gitignore', // Files to include in structure summary
//     WORKSPACE_FOLDER_CONTEXT_STRUCTURE_EXCLUDE_GITIGNORE: 'workspace-folder-context-structure-exclude.gitignore', // Files to exclude from structure summary
//     WORKSPACE_FOLDER_CONTEXT_CONTENT_INCLUDE_GITIGNORE: 'workspace-folder-context-content-include.gitignore',     // Files to include in content summary
//     WORKSPACE_FOLDER_CONTEXT_CONTENT_EXCLUDE_GITIGNORE: 'workspace-folder-context-content-exclude.gitignore'      // Files to exclude from content summary
// };
