/*
A storage folder (i.e. '.prompt-scaffold') is created in each workspace folder.
This folder will include the workspace files in the 'workspace-info' subdirectory.
If it's the root workspace, the storage folder will also include the project-info and out subdirectories.
Users configure the extension functionality by editing these files.
*/

// Describes storage folder structure
export const STORAGE_FOLDER_STRUCTURE = {
    // This exists in every storage folder (all workspaces)
    SYSTEM_INFO: 'system-info',   // Contains workspace-specific files  
    // These exist only in the workspace root's storage folder 
    WORKSPACE_INFO: 'workspace-info',       // Contains project-specific files     
    OUT: 'out'                          // Contains prompt output files generated by the extension 
};

// Describes project info files
// These control the project description and apply to entire project
export const SYSTEM_FILES = {
    SCAFFOLD_PROMPT: 'system-prompt.txt',           // Base prompt used
    SYSTEM_DESCRIPTION: 'system-description.txt',   // Description of whole system
    SESSION_GOALS: 'session-goals.txt'  // Current development session goals
};

// Describes workspace info files
// These control which files from the workspace folder are included in the context
export const WORKSPACE_FILES = {
    WORKSPACE_DESCRIPTION: 'workspace-description.txt',         // Description of specific workspace (project w/in system)
    INCLUDE_STRUCTURE_GITIGNORE: 'include.structure.gitignore', // Files to include in structure summary
    EXCLUDE_STRUCTURE_GITIGNORE: 'exclude.structure.gitignore', // Files to exclude from structure summary
    INCLUDE_CONTENT_GITIGNORE: 'include.content.gitignore',     // Files to include in content summary
    EXCLUDE_CONTENT_GITIGNORE: 'exclude.content.gitignore'      // Files to exclude from content summary
};

