export enum ProjectFileType {
    SCAFFOLD_PROMPT,
    SYSTEM_DESCRIPTION,
    SESSION_GOALS
}

export enum WorkspaceFileType {
    PROJECT_DESCRIPTION,
    INCLUDE_STRUCTURE_GITIGNORE,
    EXCLUDE_STRUCTURE_GITIGNORE,
    INCLUDE_CONTENT_GITIGNORE,
    EXCLUDE_CONTENT_GITIGNORE
}