// these files will be created in the workspace directory
export enum ProjectFolderFileType {
    SYSTEM_PROMPT,
    PROJECT_DESCRIPTION,
    SESSION_GOALS,
    CONTEXT_STRUCTURE_INCLUDE_GITIGNORE,
    CONTEXT_STRUCTURE_EXCLUDE_GITIGNORE,
    CONTEXT_CONTENT_INCLUDE_GITIGNORE,
    CONTEXT_CONTENT_EXCLUDE_GITIGNORE
}

export enum WorkspaceFolderFileType {
    PROJECT_DESCRIPTION,
    OVERRIDE_CONTEXT_STRUCTURE_INCLUDE_GITIGNORE,
    OVERRIDE_CONTEXT_STRUCTURE_EXCLUDE_GITIGNORE,
    OVERRIDE_CONTEXT_CONTENT_INCLUDE_GITIGNORE,
    OVERRIDE_CONTEXT_CONTENT_EXCLUDE_GITIGNORE
}